Online_Stor/Stor/Stor/urls.py
from django.contrib import admin
from ecomapp.views import base_view
from django.conf.urls import url, include
from django.conf import settings  #указывают джанго необходимые пути для статических файлов 
from django.conf.urls.static import static    #указывают джанго необходимые пути для статических файлов 

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^', include('ecomapp.urls')),

]


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) #когда находимся в режими локальной разработки наши пути к сатическим файлам находятся по этому адресу , в продакшени по другому адресу 
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)   #когда находимся в режими локальной разработки наши пути к сатическим файлам находятся по этому адресу , в продакшени по другому адресу 

Online_Stor/Stor/ecomapp/urls.py
from django.conf.urls import url, include
from ecomapp.views import ( 
				base_view, 
				category_view, 
				product_view, 
				cart_view, 
				add_to_cart_view, 
				remove_from_cart_view, 
				change_items_qty, 
				checkout_view, 
				order_create_view, 
				make_order_view, 
				account_view,
				registration_view,
				login_view,
				logout_view
							)
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', base_view, name='base'),
    url(r'^category/(?P<category_slug>[-\w]+)/$', category_view, name='category_detail'),
	url(r'^product/(?P<product_slug>[-\w]+)/$', product_view, name='product_detail'),
	url(r'^add_to_cart/$', add_to_cart_view, name='add_to_cart'), # добовляет товар в корзину 
	url(r'^remove_from_cart/$', remove_from_cart_view, name='remove_from_cart'), # удаляет товар из корзины
	url(r'^change_items_qty/$', change_items_qty, name='change_items_qty'),#добовления кол-ва товара 
	url(r'^checkout/$', checkout_view, name='checkout'),
	url(r'^order_create/$', order_create_view, name='order_create'),
	url(r'^make_order/$', make_order_view, name='make_order'),
	url(r'^thank_you/$', TemplateView.as_view(template_name='thank_you.html'), name='thank_you'),
	url(r'^account/$', account_view, name='account'),
	url(r'^logout/$',logout_view, name='logout'),
	url(r'^login/$', login_view, name='login'),
	url(r'^registration/$', registration_view, name='registration'),
    url(r'^cart/$', cart_view, name='cart'),
    ]

Online_Stor/Stor/ecomapp/models.py
from django.db import models 
from django.conf import settings
from django.db.models.signals import pre_save #для авто заполнения
from django.utils.text import slugify #берет поля и превращает в поле с типом slug
from django.urls import reverse  #для создания ссылок на объекты 
from transliterate import translit # библиотека для перевода с керилицы в латиницу .Установить через pip (pip install transliterate)
from mptt.models import MPTTModel, TreeForeignKey  # создает дерево 

# Create your models here.

#class Sklady(models.Model):
	#address = models.CharField(max_length=150, verbose_name="Адрес")
	#phone  = models.CharField(max_length=12, verbose_name="Телефон")
	 		



class Category (models.Model):
	name = models.CharField(max_length=150, verbose_name='Название')
	slug = models.SlugField(max_length=150, unique=True ,blank=True, verbose_name='Ссылка',)


	def __str__(self):
		return self.name

	def get_absoulute_url(self):
		return  reverse('category_detail', kwargs={'category_slug': self.slug})

	class Meta:
		verbose_name = ('Категория')
		verbose_name_plural = ('Категории')
			



def pre_save_category_slug(sender, instance, *args, **kwargs):
	if not instance.slug:
		slug = slugify(translit(unicode(instance.name), reversed=True))
		instance.slug = slug

pre_save.connect(pre_save_category_slug, sender=Category)





	



class Brand(models.Model):
	name = models.CharField(max_length=150, verbose_name='Название')

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = ('Бренд')
		verbose_name_plural = ('Бренды')


def image_folder(instance, filename):                       
		filename = instance.slug + '.' + filename.split('.')[1] #переопределяем название файла которого скачали ( filename ) который разделяет наш файл на название и его расширение 
		return "{0}/{1}".format(instance.slug, filename)  # возвращаем строку идет подсановка методом format и записываем эту функцию в upload_to

#class ProductManager(models.Model):

	 # #def all(self, *args, **kwargs):
	  	#return super(ProductManager, self).get_queryset().filter(available=True) # для того чтобы на сайте не отображался товар которого нет в наличии 
	
		

class Product(models.Model):
	category = models.ForeignKey(Category, verbose_name='категория', on_delete=models.CASCADE)
	brand = models.ForeignKey(Brand, verbose_name='брэнд', on_delete=models.CASCADE)
	#sklady = models.ManyToManyField(Sklady, verbose_name= 'Склады')
	title = models.CharField(max_length=150, verbose_name='Название',  )
	slug  = models.SlugField(max_length=150, verbose_name='Ссылка', blank=True)
	description = models.TextField(blank=True, verbose_name='Описание')
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	image = models.ImageField(upload_to=image_folder, default=True)
	price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена')
	available = models.BooleanField(default=True, verbose_name='В наличии/не в наличии')
	#objects = ProductManager()

	def __str__(self):
		return self.title

	def get_absoulute_url(self):
		return  reverse('product_detail', kwargs={'product_slug': self.slug})

	class Meta:
		verbose_name = ('Продук')
		verbose_name_plural = ('Продукты')



def pre_save_product_slug(sender, instance, *args, **kwargs):
	if not instance.slug:
		slug = slugify(translit(unicode(instance.name), reversed=True))
		instance.slug = slug
pre_save.connect(pre_save_product_slug, sender=Product)


	



class CartItem(models.Model):
	product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукты')
	qty = models.PositiveIntegerField(default=1, verbose_name='количество')
	item_total =models.DecimalField(max_digits=9, decimal_places=2, default=0.00)


	def __str__(self):
		return "Cart item for product {0}".format(self.product.title)

	class Meta:
		verbose_name = ('Элемент Корзины')
		verbose_name_plural = ('Элементы Корзин')



class Cart(models.Model):
	items = models.ManyToManyField(CartItem, blank=True)
	catr_total = models.DecimalField(max_digits=9 , decimal_places=2 , default=0.00)

	def __str__(self):
		return str(self.id)

	class Meta:
		verbose_name = ('Корзина')
		verbose_name_plural = ('Корзины')



	def add_to_cart(self, product_slug):
		cart = self
		product = Product.objects.get(slug=product_slug)
		new_item, _= CartItem.objects.get_or_create(product = product, item_total=product.price)  
		if new_item not in cart.items.all():
			cart.items.add(new_item)
			cart.save()

	def remove_from_cart(self, product_slug):
		cart = self
		product = Product.objects.get(slug=product_slug)
		for cart_item in cart.items.all():
			if cart_item.product == product:
				cart.items.remove(cart_item)
				cart.save()



	def change_qty(self, qty, item_id):
		cart = self
		cart_item = CartItem.objects.get(id=int(item_id))
		cart_item.qty = int(qty)
		cart_item.item_total = int(qty)* float(cart_item.product.price)
		cart_item.save()
		new_cart_total = 0.00
		for item in cart.items.all():
			new_cart_total += float(item.item_total)
		cart.catr_total = new_cart_total
		cart.save()


ORDER_STATUS_CHOICES = (
	('принят в обработку', 'принят в обработку' ),
	('Выполняется','Выполняется'),
	('Оплачен','Оплачен')
)

class Order(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	status = models.CharField(max_length=200, choices=ORDER_STATUS_CHOICES, default=ORDER_STATUS_CHOICES[0][0] , verbose_name='Статус заказа')
	items = models.ManyToManyField(Cart)
	buying_type = models.CharField(max_length=40, choices=(('Самовывоз','Самовывоз' ),('Доставка','Доставка')), default='Самовывоз', verbose_name='тип заказа')
	total = models.DecimalField(max_digits=9 , decimal_places=2 , default=0.00, verbose_name='Общая сумма')
	order_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')
	first_name = models.CharField(max_length=150, verbose_name='Имя')
	surname  = models.CharField(max_length=150, verbose_name='Фамилия')
	phone = models.CharField(max_length=12, verbose_name='Телефон')
	user_email = models.EmailField(max_length=200, verbose_name='почта пользователя ')
	address = models.CharField(max_length=600, verbose_name='Адрес')
	comments = models.TextField(verbose_name='комментарии')

	def __str__(self):
		return "Заказ №{0}".format(str(self.id))

	class Meta:
		verbose_name = ('Заказ')
		verbose_name_plural = ('Заказы')





		

			
	
		




	


	

Online_Stor/Stor/ecomapp/forms.py
# -*- coding: utf-8 -*-



from django import forms
from django.utils import timezone
from django.contrib.auth.models import User

class LoginForm(forms.Form):

	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)

	def __init__(self, *args, **kwargs):
		super(LoginForm, self).__init__(*args, **kwargs)
		self.fields['username'].label = 'Логин'
		self.fields['password'].label = 'Пароль'

	def clean(self):
		username = self.cleaned_data['username']
		password = self.cleaned_data['password']
		if not User.objects.filter(username=username).exists():
			raise forms.ValidationError('Пользователь с данным логином не зарегистрирован в системе!')
		user = User.objects.get(username=username)
		if user and not user.check_password(password):
			raise forms.ValidationError('Неверный пароль!')
			
	
		


class RegistrationForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	password_check = forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = [ 									 #указываем поля 
			'username',
			'password',
			'password_check',
			'first_name',
			'last_name',
			'email'
		]
		
	def __init__(self, *args, **kwargs):
		super(RegistrationForm, self).__init__(*args, **kwargs)
		self.fields['username'].label = 'Логин'
		self.fields['password'].label = 'Пароль'
		self.fields['password'].help_text = 'Придумайте пароль'
		self.fields['password_check'].label = 'Повторите пароль'
		self.fields['password_check'].help_text = 'Повторите пароль'
		self.fields['first_name'].label = 'Имя'
		self.fields['last_name'].label ='Фамилия'
		self.fields['email'].label = 'Ваша почта'
		self.fields['email'].help_text = 'Пожалуйста, указывайте реальный адрес'

	def clean(self):																	#создаем проверку 
		username = self.cleaned_data['username']
		password = self.cleaned_data['password']
		password_check = self.cleaned_data['password_check']
		email = self.cleaned_data['email']
		if User.objects.filter(username=username).exists():
			raise forms.ValidationError('Пользователь с данным логином уже зарегистрирован в системе!')
		if password != password_check:
			raise forms.ValidationError('Ваши пароли не совпадают! Попробуйте снова!')
		if User.objects.filter(email=email).exists():
			raise forms.ValidationError('Пользователь с данной почтой уже зарегистрирован в системе!')

class OrderForm(forms.Form):
	first_name = forms.CharField(max_length=150)
	surname  = forms.CharField(max_length=150)
	phone = forms.CharField(max_length=12)
	buying_type = forms.ChoiceField(widget=forms.Select(), choices=(('self','Самовывоз' ),('delivery','Доставка'))) # widget=froms.Select()-выпадающее меню; choices=(('...','...'),('...'),('...'))-выбор выпадающего меню!
	date = forms.DateField(widget=forms.SelectDateWidget(), initial=timezone.now())
	user_email = forms.EmailField(max_length=200)
	address = forms.CharField(required=False)
	comments = forms.CharField(widget=forms.Textarea, required=False)

	def __init__(self, *args, **kwargs):
		super(OrderForm, self).__init__(*args, **kwargs)
		self.fields['first_name'].label = 'Имя '
		self.fields['surname'].label = 'Фамилия '
		self.fields['phone'].label = ' Телефон '
		self.fields['phone'].help_text = ' Пожалуйста укажите свой номер телефона '
		self.fields['buying_type'].label = ' Способ получения  '
		self.fields['address'].label = ' Адрес доставки '
		self.fields['address'].help_text = ' Укажите свой Адрес: Страна/Регион-Край/Область/Регион-Город-Улица, дом, квартира '
		self.fields['user_email'].label = ' почта "email" '
		self.fields['user_email'].help_text = ' Укажите Вашу почту  '
		self.fields['comments'].label = 'Комментарии'
		self.fields['date'].label = ' Дата доставки '
		self.fields['date'].help_text = ' Доставка производится на следущий день после оформления заказа. Менеджер с Вами предварительно свяжется! '



		#скачать ещё нужно для html шаблона библиотеку django 'django-crispy-forms'!!!
		#после этого в файле settings.py  в самом незу прописать CRISPY_TEMPLATE_PACK = ' bootstrap3' 
		#и заинсталировать в crispy_forms В settings.py В разделе INSTALL_APP
	

Online_Stor/Stor/ecomapp/templates/account.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<h3 class="text-center" > Личный кабинет {{ request.user}} </h3>
<hr>
<div class="order-list">
		<h4 class="text-center"> Ваши заказы</h4>
		<table class="table" >
		{% for item in order %}
				<tr class="text-center" style="background: lightblue;">
					<td>Номер заказа</td>
					<td>Дата заказа</td>
					<td>Статус заказа</td>
					<td>Стоимость заказа</td>
					<td>Способ доставки</td>
					
					<td></td>
				</tr>
			
				<tr class="text-center">
					<td>{{ item.id }}</td>
					<td>{{ item.order_date}}</td>
					<td>{{ item.status }}</td>
					<td>{{ item.total }}</td>
					
					<td><button type="button" class="btn btn-primary btn-md" data-toggle="modal" data-target="#myModal-{{ item.id }}"> Детали заказа</button></td>
			

		{% endfor %}
		</table >
{% for item in order %}
<div class="modal fade" id="myModal-{{ item.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Заказ № {{ item.id }}</h4>
      </div>
      <div class="modal-body">
      	<h3 class="text-center">Товар</h3>
        	<table class="table">
        	{% for order_item in item.items.all %}
        		<tr class="text-center">
        			<td>Название товара</td>
        			<td>кол-во</td>
        			<td>цена</td>
        		</tr>
      			{% for ord_item in order_item.items.all %}	
        		<tr class="text-center">
        			<td>{{ ord_item.product.title }}</td>
        			<td>{{ ord_item.qty }} шт.</td>
        			<td>{{ ord_item.item_total }} руб.</td>
        		</tr>
        		{% endfor %}
        		<tr>
        			<td></td>
        			<td><strong>ИТОГО:</strong></td>
        			<td><strong> {{ order_item.catr_total }} руб.</strong></td>
        		</tr>
        	{% endfor %}
        	</table>
        	<h3 class="text-left">Заказчик</h3>
      		<p>Имя: {{ item.first_name }} </p>
      		<p>Фамилия: {{ item.surname }}</p>
      		<p>Телефон: {{ item.phone }}</p>
      		<h3 class="text-left">Тип доставки</h3>
      		<div>
      			<p> {{item.buying_type}} </p>
      			<p>	{{item.address}} </p>
      		</div>
      		<h3 class="text-left">Коментарии к заказу</h3>
      		<p> {{ item.comments }} </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
	{% endfor %}
{% endblock content %}

Online_Stor/Stor/ecomapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Shop Homepage - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/shop-homepage.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>

    <!-- Navigation -->
    
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
     
        <div class="container">
       

        	
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Start Bootstrap</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                {% if not request.get_full_path == '/' %}
                   <li class="dropdown">
	                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Категории <span class="caret"></span></a>
	                  <ul class="dropdown-menu">
	                  	 {% for category in categories %}
	                       <li><a href="{{category.get_absoulute_url}}">{{category.name}}</a></li>
	                     {% endfor %}
	                  </ul>
	                </li>
	            {% endif %}

	            <li><p class="navbar-text" >
                	{% if not request.user.is_authenticated %}
                					<a href="{% url 'registration' %}"><button class="btn btn-info">Регистрация</button></a>
									<a href="{% url 'login' %}"><button class="btn btn-info">Войти</button></a>
            			{% else %} 
            			<li>
            			 	<p class="navbar-text" >Здравствуйте,  {{ request.user }}!</p>
            			 </li>
            			<li>
								<a href='{% url "account" %}'>Личный кабинет</a>
						</li>

						<li>
							<a href="{% url 'logout' %}">Выйти</a>
						</li>

            			 {% endif %} 
                        <div class="nav navbar-nav" style="padding-top: 10px; padding-bottom: 15px; padding-left: 15px;">
                            <form method='GET' action="" >
                                 <input type="text" name="q" placeholder='Search post'/>
                                <input type='submit' value='Search'/>
                            </form>
                        </div>

            	</p></li>﻿


                </ul>
                <ul class="nav navbar-nav navbar-right">
                	<li><a href='{% url "cart" %}'>Корзина<span class='badge' id='cart_count'>{% if not request.session.total %} 0 {% else %} {{request.session.total}} {% endif %} </span></a></li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container" style="margin-top: 2	%;">
    	{% block content %}

        <div class="row">

            <div class="col-md-3">
                <p class="lead">Категории</p>
                <div class="list-group">
                    {% for category in categories %}
                    <p class="text-center" style="font-size:15px;">
                    	<strong>
                    		<a href="{{ category.get_absoulute_url }}" class="list-group-item">{{ category.name }}</a>
                    	</strong>
                    </p>
                    {% endfor %}
                </div>
            </div>

            <div class="col-md-9">

                <div class="row carousel-holder">

                    <div class="col-md-12">
                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                            	{% for product in products %}
                            		{% if forloop.first %}
		                                <div class="item active">
		                                    <img class="slide-image" src="{{ product.image.url }}" alt="" style='padding-left: 450px;width:800px; height: 300px;'>
		                                    <br>
		                                    <p class='text-center'><a href='{{ product.get_absoulute_url }}'><button class='btn btn-primary'>{{ product.title }}</button></a></p>
		                                    <p class="text-center"><a  href='#' class='add_to_cart' data-slug = '{{ product.slug }}'><button class="btn btn-danger">Добавить в корзину</button></a></p>
		                                </div>
		                            {% else %}
		                                <div class="item">
		                                    <img class="slide-image" src="{{ product.image.url }}" alt="" style='padding-left: 450px;width:800px; height: 300px;'>
		                                    <br>
		                             		<p class='text-center'><a href='{{ product.get_absoulute_url }}'><button class='btn btn-primary'>{{ product.title }}</button></a></p>
		                                    <p class="text-center"><a  href='#' class='add_to_cart' data-slug = '{{ product.slug }}'><button class="btn btn-danger">Добавить в корзину</button></a></p>
		                                </div>
		                            {% endif %}
                                {% endfor %}
                            </div>
                            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev" style='background: transparent;'>
                                <span class="glyphicon glyphicon-chevron-left" style='color:black;'></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next" style='background: transparent;'>
                                <span class="glyphicon glyphicon-chevron-right" style='color:black;'></span>
                            </a>
                        </div>
                    </div>

                </div>

                <br>

                <div class="row">
                    {%for product in products %}
                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail" style='height: 410px; position: relative;'>
                            <img src="{{ product.image.url }}" alt="" style="width: 100%; height: 250px;">
                            <div class="caption">
                                <h6><a href="{{product.get_absoulute_url}}"><strong>{{product.title}}</strong></a></h6>

                                <p class=" text-center"><h5 class="pull-right">{{product.price}}  ₽.</h5></p>
                               	<div style='position: absolute; bottom: 0; right:40px;'>  
                                	{% if request.user.in_authenticated %}<p class="text-center"><a  href='#' class='add_to_cart' data-slug = '{{ product.slug }}'><button class="btn btn-danger">Добавить в корзину</button></a></p>
                                	{% else %}<p class="text-center"><a  href='#' class='add_to_cart' data-slug = '{{ product.slug }}'><button class="btn btn-danger">Добавить в корзину</button></a></p>
                               		{% endif %}
                                </div>
                            </div>
                        </div>
                     </div>
                    {% endfor %}
                </div>
                 
                </div>

        
            </div>
        {% endblock content %}    

        </div>

    
        
    </div>
  

    <!-- /.container -->

    <div class="container">
    	

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </footer>
        
    </div>
    <!-- /.container -->

    <!-- jQuery -->
  
   <!-- jQuery -->

    <script src="{% static 'js/jquery.js' %}"></script>
   
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

<script>
	$(document).ready(function(){
			$('.add_to_cart').on('click', function(e){
				e.preventDefault()
				product_slug = $(this).attr('data-slug')
				data = {
					product_slug: product_slug
					   }
				$.ajax({
					type: "GET",
					url: '{% url "add_to_cart" %}',
					data: data,
					success: function(data){
						$("#cart_count").html(data.cart_total)
					}
				})
			})	
		})
</script>



</body>

</html>

Online_Stor/Stor/ecomapp/templates/checkout.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<h3 class="text-center" ><strong>Ваша предворительный заказ</strong></h3>
<table class="table">
<tr>
	<td class="text-center"><strong>Товар</strong></td>
	<td class="text-center"><strong>Кол-во</strong></td>
	<td class="text-center"><strong>Цена</strong></td>
	<td class="text-center"><strong></strong></td>
</tr>	
{% for item in cart.items.all %}
<tr>
	<td class="text-center" >{{ item.product.title }}</td> 
	<td class="text-center" >{{item.qty}}</td>
	<td class='text-center' >{{ item.item_total }} руб.</td>
	<td></td>
</tr>
{% endfor %}
<tr>
	<td></td>
	<td class="text-center"><strong>ИТОГО:</strong></td>
	<td class="text-center"><strong>{{ cart.catr_total }} </strong><strong>руб.</strong></strong></td>
	<td></td>
</tr>
</table>
<a href="{% url 'order_create' %}" class="pull-right"><button class="btn btn-info" >Оформить заказ</button></a>









{% endblock content %}

Online_Stor/Stor/ecomapp/templates/order.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<form action="{% url 'make_order' %}" method="POST">
				{% csrf_token %}

	<div class='col-sm-4' style="text-align: left;">		
		{{ form.first_name|as_crispy_field }}

		{{ form.user_email|as_crispy_field }}
	</div>

	<div class='col-sm-4' style="text-align: left;">
		{{ form.surname|as_crispy_field }}

		{{ form.phone|as_crispy_field }}
	</div>

	<div class='col-sm-10' style="text-align: left;">
		{{ form.date|as_crispy_field }}
		{{ form.buying_type|as_crispy_field }}
		{{ form.address|as_crispy_field }}
		{{ form.comments|as_crispy_field }}
	</div>

	<div class='col-sm-10' style="text-align: left;">

		<input type='submit' class='btn btn-info' value='Оформить заказ'>

	</div>
</form>
	
<script src="{% static 'js/jquery.js' %}"></script>
<script>
$(document).ready(function(){
	$('#div_id_address').css('display', 'none')
	$('#id_buying_type').on('click', function(){
			buying_type = $(this).val()
			if (buying_type == 'delivery'){
				$('#div_id_address').css('display', 'block')
			}
			else{
				$('#div_id_address').css('display','none')
			}

	})
	$('#id_first_name').css('width', '300px')
	$('#id_surname').css('width', '300px')
	$('#id_user_email').css('width', '300px')
	$('#id_phone').css('width', '300px')
	$('#id_buying_type').css('width', '300px')
	$('#id_date_day').css('width', '60px').css('display', 'inline')
	$('#id_date_month').css('width', '100px').css('display', 'inline')
	$('#id_date_year').css('width', '100px').css('display', 'inline')﻿
})

</script>
{% endblock content %}